### ISSUE TITLE
How to query / filter a single word file?

### ISSUE THREAD

**Issue by WernMich** [opszero/gatsby-transformer-ms-word#1]
Hi,

first at all: I am a newby regarding React, GraphQL and Gatsby. 

I am wondering how to use this transformer plugin to query / address a single word file and not all word files within a directory as it is done in the sample. 

I am looking for a way to filter for a single file.

I was looking in the sources of mammoth.js and this transformer but I did not find a definition of `allDocx`. Where does this come from? Is there a "singleDocx" or sth. similar like querying for a file with filters (e.g. `file(relativePath: { eq: "./SiteAContent.docx" })`)?

**Comment by abhiyerra** [comment]
Unfortunately, I don't know. I stepped off of using GatsbyJS and am not
actively developing this plugin. So if you know the answer I'd love if
you'd send a pull request!
